services:
  db:
    image: mongo:8
    command: mongod --quiet --logpath /dev/null
    environment:
      - MONGO_INITDB_ROOT_USERNAME=db_user
      - MONGO_INITDB_ROOT_PASSWORD=db_p4ssw0rd
    volumes:
      - type: bind
        source: ./db/data
        target: /data/db
      - ./db/image/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
  api:
    build: ./api
    environment:
      - MONGO_URI=mongodb://db_user:db_p4ssw0rd@db:27017/application?authSource=admin
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./api/src:/app/src
  ws-api:
    build: ./ws-api
    env_file:
      - ./.env
    ports:
      - 3001:3001
    depends_on:
      - api
    environment:
      - API_URL=http://api:3000
    volumes:
      - ./ws-api/src:/app/src